#! /bin/bash

curl -X POST http://localhost:8000/Neha-sanserwal
curl -X POST http://localhost:8000/abhilashkasula
curl -X POST http://localhost:8000/anil-muraleedharan
curl -X POST http://localhost:8000/anujachaitanya
curl -X POST http://localhost:8000/apurvagurme
curl -X POST http://localhost:8000/armanaaquib
curl -X POST http://localhost:8000/bcalm
curl -X POST http://localhost:8000/bernie-walker
curl -X POST http://localhost:8000/bsanthoshkumar
curl -X POST http://localhost:8000/bugdriver
curl -X POST http://localhost:8000/cricket-lover
curl -X POST http://localhost:8000/dad-ka-raneesa
curl -X POST http://localhost:8000/desibabua
curl -X POST http://localhost:8000/drishya-dobriyal
curl -X POST http://localhost:8000/gulsane
curl -X POST http://localhost:8000/imvaishu
curl -X POST http://localhost:8000/lazyhackerthani
curl -X POST http://localhost:8000/melodyni
curl -X POST http://localhost:8000/mildshower
curl -X POST http://localhost:8000/myultimatevision
curl -X POST http://localhost:8000/naveen-kumar-vadla
curl -X POST http://localhost:8000/nooranasrin
curl -X POST http://localhost:8000/palpriyanshu
curl -X POST http://localhost:8000/photongupta
curl -X POST http://localhost:8000/pssruthy
curl -X POST http://localhost:8000/rahitkar
curl -X POST http://localhost:8000/rey-vthi
curl -X POST http://localhost:8000/satheesh-chandran
curl -X POST http://localhost:8000/shankarbyageli
curl -X POST http://localhost:8000/shiviraj
curl -X POST http://localhost:8000/sravani-labala
curl -X POST http://localhost:8000/sukhiboi
curl -X POST http://localhost:8000/symbiote-ux
curl -X POST http://localhost:8000/trinangkur
curl -X POST http://localhost:8000/unphydra
curl -X POST http://localhost:8000/venkybavisetti
curl -X POST http://localhost:8000/craftybones
curl -X POST http://localhost:8000/vharidas
curl -X POST http://localhost:8000/blpabhishek